name: seattle-flu
channels:
  - r
  - conda-forge
  - bioconda
  - biobuilds
  - defaults
dependencies:
  - bamstats
  - bcftools
  - biopython
  - bowtie2
  - curl
  - fastqc
  - jupyterlab
  - matplotlib
  - nb_conda_kernels
  - ncurses=6.1
  - picard
  - python=3.6
  - r-essentials
  - rpy2
  - samtools
  - seaborn
  - seqkit
  - snakemake
  - tabix
  - trimmomatic
  - varscan
  - vcftools
  - xlrd
